# Generated by Django 3.0.8 on 2020-08-10 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200810_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topped_expired_time',
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('topped_expired_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='置顶失效时间')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Post', verbose_name='文章')),
            ],
            options={
                'verbose_name': '置顶',
                'verbose_name_plural': '置顶',
            },
        ),
    ]
