# Generated by Django 3.0.8 on 2020-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('post_id', models.PositiveIntegerField(verbose_name='关联文章ID')),
            ],
        ),
    ]
