# Generated by Django 3.0.8 on 2020-08-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200810_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='Post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='文章'),
        ),
    ]
