# Generated by Django 3.0.8 on 2020-08-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200810_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='Post',
        ),
        migrations.AddField(
            model_name='post',
            name='top',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Top', verbose_name='置顶'),
        ),
    ]
